// Generated by CoffeeScript 1.9.1
var CONF, es_get_all, es_put;

CONF = {
  DB: location.host.startsWith('localhost') ? 'http://localhost:9200' : 'SOMETHING'
};

$.ajax({
  url: CONF.DB,
  type: 'GET',
  success: function(data) {
    return console.log(data);
  }
});

es_put = function(index_name, type_name, data) {
  return $.ajax({
    url: CONF.DB + "/" + index_name + "/" + type_name + "/",
    type: 'POST',
    data: JSON.stringify(data),
    success: function(data) {
      return console.log(data);
    },
    error: function(error) {
      return console.log(error.responseText);
    }
  });
};

es_get_all = function(index_name, type_name, callback) {
  return $.ajax({
    url: CONF.DB + "/" + index_name + "/" + type_name + "/_search",
    type: 'GET',
    success: function(data) {
      return callback(data);
    }
  });
};

//# sourceMappingURL=main.js.map
