// Generated by CoffeeScript 1.9.1
var client, es_get_all, es_put;

$.ajax({
  url: "http://localhost:9200",
  type: 'GET',
  success: function(data) {
    return console.log(data);
  }
});

es_put = function(index_name, type_name, data) {
  return $.ajax({
    url: "http://localhost:9200/" + index_name + "/" + type_name + "/",
    type: 'POST',
    data: JSON.stringify(data),
    success: function(data) {
      return console.log(data);
    },
    error: function(error) {
      return console.log(error.responseText);
    }
  });
};

es_get_all = function(index_name, type_name, callback) {
  return $.ajax({
    url: "http://localhost:9200/" + index_name + "/" + type_name + "/_search",
    type: 'GET',
    success: function(data) {
      return callback(data);
    }
  });
};

client = new $.es.Client({
  hosts: 'localhost:9200'
});

client.ping({
  requestTimeout: 30000,
  hello: "elasticsearch!"
}, function(error) {
  if (error) {
    return console.error('elasticsearch cluster is down!');
  } else {
    return console.log('All is well');
  }
});

client.search({
  index: 'twitter',
  type: 'tweet',
  body: {
    query: {
      term: {
        'message': 'elasticsearch'
      }
    }
  }
}).then(function(resp) {
  return console.log(resp);
}, function(err) {
  return console.trace(err.message);
});

es_get_all('twitter', 'tweet', function(d) {
  return console.log(d);
});

//# sourceMappingURL=main.js.map
